name: "Управление поливом"
version: "0.2.14"
slug: "irrigation_manager"
description: "Simple Home Assistant irrigation program manager with sequential zone control"
arch:
  - amd64
  - aarch64
startup: application
boot: auto
panel_icon: mdi:sprinkler-variant
panel_title: Управление поливом
ingress: true
ingress_port: 8000
ports:
  8000/tcp: 8010
hassio_api: true
homeassistant_api: true
map:
  - addon_config:rw
